### ISSUE TITLE
Support sendfile/TransmitFile

### ISSUE THREAD

**Issue by henke37** [libsdl-org/SDL_net#38]
The `sendfile` and `TransmitFile` functions are optimized for sending data from file handles to socket handles.

It would be rather nice to have this functionality, both for efficiency and for ease of use.

**Comment by icculus** [comment]
My thinking is this isn't worthwhile; these APIs were added for web servers to feed files to clients more efficiently when you have lots of clients downloading lots of static files, and it's not usually useful in any other situation. It's likely a little more efficient than feeding files through a socket in blocks (but I question how much), and it's completely unusable once you move from HTTP to HTTPS, since you need to transform the data between the file and the socket.
